# Generated by Django 4.2.18 on 2025-01-23 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(default='N/A', editable=False, max_length=100)),
                ('employee_type', models.CharField(default='N/A', editable=False, max_length=100)),
                ('employee_email', models.CharField(default='N/A', editable=False, max_length=100)),
                ('clicked_link', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scheme_name', models.CharField(editable=False, max_length=100)),
                ('email_file', models.FileField(upload_to='upload/receiver_email_data')),
                ('email_subject', models.CharField(editable=False, max_length=2000)),
                ('email_body', models.CharField(editable=False, max_length=2000)),
            ],
        ),
    ]
